# SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
#
# SPDX-License-Identifier: Apache-2.0

services:
  citrine-ui:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
       NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://hasura.example.com/v1/graphql}
       NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-wss://hasura.example.com/v1/graphql}
       NEXT_PUBLIC_CITRINE_CORE_URL: ${NEXT_PUBLIC_CITRINE_CORE_URL:-https://core.example.com}
       NEXT_PUBLIC_FILE_SERVER_URL: ${NEXT_PUBLIC_FILE_SERVER_URL:-https://files.example.com}
       NEXTAUTH_URL: ${NEXTAUTH_URL:-https://ui.example.com}

    ports:
      - 3000:3000
    environment: 
      HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET:-replace-me}
      NEXT_PUBLIC_DEFAULT_MAP_CENTER_LATITUDE: 39.833333 # The visual center of the contiguous USA.
      NEXT_PUBLIC_DEFAULT_MAP_CENTER_LONGITUDE: -98.583333 # The visual center of the contiguous USA.
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://hasura.example.com/v1/graphql}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-wss://hasura.example.com/v1/graphql}
      NEXT_PUBLIC_CITRINE_CORE_URL: ${NEXT_PUBLIC_CITRINE_CORE_URL:-https://core.example.com}
      NEXT_PUBLIC_FILE_SERVER_URL: ${NEXT_PUBLIC_FILE_SERVER_URL:-https://files.example.com}
      NEXT_PUBLIC_LOGO_URL: https://d1h8867rcwtfcw.cloudfront.net/logo-collapsed.svg
      NEXT_PUBLIC_METRICS_URL: ${NEXT_PUBLIC_METRICS_URL:-https://metrics.example.com/v1/metrics}
      NEXT_PUBLIC_ADMIN_EMAIL: admin@citrineos.com
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-replace-me}
      NEXT_PUBLIC_BANNER_MESSAGE: OCPP 2.1 Now Available!
      NEXTAUTH_URL: ${NEXTAUTH_URL:-https://ui.example.com}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-replace-me}
      ALLOW_IMAGE_UPLOAD: false